/**
 * Key Manager for SSH MCP Server
 * 
 * Manages SSH key operations using ssh-keygen and ssh-add binaries.
 * Handles key generation, validation, fingerprint computation, and ssh-agent integration.
 */

import { spawn } from 'child_process';
import { promises as fs } from 'fs';
import { join, dirname } from 'path';
import type { KeyPair, KeyInfo } from './types.js';
import { scrubSensitiveData } from './SecurityUtils.js';

/**
 * Options for key generation
 */
export interface KeyGenerationOptions {
  /** Key algorithm (rsa, ed25519, ecdsa, etc.) */
  algorithm: string;
  
  /** Key size in bits */
  bits: number;
  
  /** Passphrase for the private key (optional) */
  passphrase?: string;
  
  /** Path where the key should be saved (optional, defaults to ~/.ssh/id_{algorithm}_{timestamp}) */
  path?: string;
  
  /** Comment for the key (optional) */
  comment?: string;
}

/**
 * Result of executing a subprocess command
 */
interface SubprocessResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/**
 * KeyManager handles SSH key operations using openssh-portable tools
 */
export class KeyManager {
  private sshKeygenPath: string;
  private sshAddPath: string;
  private debugLevel: number;

  /**
   * Create a new KeyManager instance
   * @param sshKeygenPath - Path to ssh-keygen binary (defaults to 'ssh-keygen')
   * @param sshAddPath - Path to ssh-add binary (defaults to 'ssh-add')
   * @param debugLevel - Debug verbosity level 0-3 (optional, defaults to 0)
   */
  constructor(
    sshKeygenPath: string = 'ssh-keygen',
    sshAddPath: string = 'ssh-add',
    debugLevel: number = 0
  ) {
    this.sshKeygenPath = sshKeygenPath;
    this.sshAddPath = sshAddPath;
    this.debugLevel = debugLevel;
  }

  /**
   * Generate a new SSH key pair
   * @param options - Key generation options
   * @returns KeyPair information including paths and fingerprint
   */
  async generateKey(options: KeyGenerationOptions): Promise<KeyPair> {
    const { algorithm, bits, passphrase, path, comment } = options;

    // Determine key path
    const keyPath = path || this.getDefaultKeyPath(algorithm);
    
    // Ensure directory exists
    await this.ensureDirectoryExists(dirname(keyPath));

    // Build ssh-keygen command
    const args = [
      '-t', algorithm,
      '-b', bits.toString(),
      '-f', keyPath,
      '-N', passphrase || '',  // Empty string for no passphrase
    ];

    if (comment) {
      args.push('-C', comment);
    } else {
      args.push('-C', `Generated by SSH MCP Server at ${new Date().toISOString()}`);
    }

    // Add debug flags if enabled
    for (let i = 0; i < this.debugLevel; i++) {
      args.push('-v');
    }

    // Execute ssh-keygen
    const result = await this.executeCommand(this.sshKeygenPath, args);

    if (result.exitCode !== 0) {
      throw new Error(`Key generation failed: ${scrubSensitiveData(result.stderr)}`);
    }

    // Get fingerprint of the generated key
    const fingerprint = await this.getFingerprint(keyPath);

    return {
      privateKeyPath: keyPath,
      publicKeyPath: `${keyPath}.pub`,
      fingerprint,
      algorithm,
      bits,
    };
  }

  /**
   * Extract public key from a private key file
   * @param privateKeyPath - Path to the private key file
   * @returns Public key string
   */
  async extractPublicKey(privateKeyPath: string): Promise<string> {
    // Execute: ssh-keygen -y -f <privateKeyPath>
    const result = await this.executeCommand(this.sshKeygenPath, [
      '-y',
      '-f', privateKeyPath,
    ]);

    if (result.exitCode !== 0) {
      throw new Error(`Failed to extract public key: ${scrubSensitiveData(result.stderr)}`);
    }

    return result.stdout.trim();
  }

  /**
   * Compute fingerprint of an SSH key
   * @param keyPath - Path to the key file (public or private)
   * @returns Key fingerprint (SHA256 hash)
   */
  async getFingerprint(keyPath: string): Promise<string> {
    // Execute: ssh-keygen -lf <keyPath>
    const result = await this.executeCommand(this.sshKeygenPath, [
      '-lf', keyPath,
    ]);

    if (result.exitCode !== 0) {
      throw new Error(`Failed to get fingerprint: ${scrubSensitiveData(result.stderr)}`);
    }

    // Output format: "2048 SHA256:abc123... comment (RSA)"
    const match = result.stdout.match(/\d+\s+(SHA256:[^\s]+)/);
    if (!match) {
      throw new Error(`Failed to parse fingerprint from output: ${result.stdout}`);
    }

    return match[1];
  }

  /**
   * List SSH keys in a directory
   * @param directory - Directory to scan for keys (defaults to ~/.ssh)
   * @returns Array of KeyInfo objects
   */
  async listKeys(directory?: string): Promise<KeyInfo[]> {
    const keyDir = directory || this.getDefaultSSHDirectory();
    
    try {
      const files = await fs.readdir(keyDir);
      const keyInfos: KeyInfo[] = [];

      // Filter for potential key files (exclude .pub files, known_hosts, config, etc.)
      const potentialKeys = files.filter(file => 
        !file.endsWith('.pub') && 
        !file.includes('known_hosts') &&
        !file.includes('config') &&
        !file.includes('authorized_keys') &&
        file.startsWith('id_')
      );

      for (const file of potentialKeys) {
        const keyPath = join(keyDir, file);
        
        try {
          const keyInfo = await this.getKeyInfo(keyPath);
          keyInfos.push(keyInfo);
        } catch (error) {
          // Skip files that aren't valid keys
          continue;
        }
      }

      return keyInfos;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return []; // Directory doesn't exist, return empty array
      }
      throw error;
    }
  }

  /**
   * Get detailed information about a specific key
   * @param keyPath - Path to the key file
   * @returns KeyInfo object
   */
  async getKeyInfo(keyPath: string): Promise<KeyInfo> {
    // Execute: ssh-keygen -lf <keyPath>
    const result = await this.executeCommand(this.sshKeygenPath, [
      '-lf', keyPath,
    ]);

    if (result.exitCode !== 0) {
      throw new Error(`Failed to get key info: ${scrubSensitiveData(result.stderr)}`);
    }

    // Output format: "2048 SHA256:abc123... comment (RSA)"
    const match = result.stdout.match(/^(\d+)\s+(SHA256:[^\s]+)\s+(.+?)\s+\(([^)]+)\)/);
    if (!match) {
      throw new Error(`Failed to parse key info from output: ${result.stdout}`);
    }

    const [, bitsStr, fingerprint, comment, type] = match;

    return {
      path: keyPath,
      type: type.toLowerCase(),
      bits: parseInt(bitsStr, 10),
      fingerprint,
      comment: comment.trim(),
    };
  }

  /**
   * Validate that a file is a valid SSH key
   * @param keyPath - Path to the key file
   * @returns True if valid, false otherwise
   */
  async validateKey(keyPath: string): Promise<boolean> {
    try {
      // Try to get key info - if it succeeds, the key is valid
      await this.getKeyInfo(keyPath);
      return true;
    } catch (error) {
      return false;
    }
  }

  /**
   * Add a key to ssh-agent
   * @param keyPath - Path to the private key file
   * @param passphrase - Passphrase for the key (optional)
   */
  async addToAgent(keyPath: string, passphrase?: string): Promise<void> {
    const args = [keyPath];

    // Execute ssh-add
    const result = await this.executeCommand(
      this.sshAddPath,
      args,
      passphrase ? { stdin: passphrase + '\n' } : undefined
    );

    if (result.exitCode !== 0) {
      throw new Error(`Failed to add key to agent: ${scrubSensitiveData(result.stderr)}`);
    }
  }

  /**
   * Execute a command and return the result
   * @param command - Command to execute
   * @param args - Command arguments
   * @param options - Execution options
   * @returns Subprocess result
   */
  private async executeCommand(
    command: string,
    args: string[],
    options?: { stdin?: string }
  ): Promise<SubprocessResult> {
    return new Promise((resolve, reject) => {
      const proc = spawn(command, args, {
        stdio: options?.stdin ? 'pipe' : 'pipe',
      });

      let stdout = '';
      let stderr = '';

      proc.stdout?.on('data', (data) => {
        stdout += data.toString();
      });

      proc.stderr?.on('data', (data) => {
        stderr += data.toString();
      });

      proc.on('error', (error) => {
        reject(new Error(`Failed to execute ${command}: ${scrubSensitiveData(error.message)}`));
      });

      proc.on('close', (code) => {
        resolve({
          stdout,
          stderr,
          exitCode: code || 0,
        });
      });

      // Write stdin if provided
      if (options?.stdin && proc.stdin) {
        proc.stdin.write(options.stdin);
        proc.stdin.end();
      }
    });
  }

  /**
   * Get the default SSH directory path
   * @returns Path to ~/.ssh directory
   */
  private getDefaultSSHDirectory(): string {
    const homeDir = process.env.HOME || process.env.USERPROFILE || '';
    return join(homeDir, '.ssh');
  }

  /**
   * Get the default key path for a given algorithm
   * @param algorithm - Key algorithm
   * @returns Default key path
   */
  private getDefaultKeyPath(algorithm: string): string {
    const sshDir = this.getDefaultSSHDirectory();
    const timestamp = Date.now();
    return join(sshDir, `id_${algorithm}_${timestamp}`);
  }

  /**
   * Ensure a directory exists, creating it if necessary
   * @param dirPath - Directory path
   */
  private async ensureDirectoryExists(dirPath: string): Promise<void> {
    try {
      await fs.mkdir(dirPath, { recursive: true, mode: 0o700 });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') {
        throw error;
      }
    }
  }

  /**
   * Get the debug verbosity level
   * 
   * @returns Debug level (0-3)
   * 
   * Validates: Requirement 10.7
   */
  getDebugLevel(): number {
    return this.debugLevel;
  }

  /**
   * Set the debug verbosity level
   * 
   * Configures the debug level for key management operations:
   * - 0: No debug output (default)
   * - 1: Basic debug output (-v flag)
   * - 2: Detailed debug output (-vv flag)
   * - 3: Maximum debug output (-vvv flag)
   * 
   * @param level - Debug level (0-3)
   * @throws Error if level is not 0, 1, 2, or 3
   * 
   * Validates: Requirement 10.7
   */
  setDebugLevel(level: number): void {
    if (![0, 1, 2, 3].includes(level)) {
      throw new Error(`Invalid debug level: ${level}. Must be 0, 1, 2, or 3.`);
    }
    this.debugLevel = level;
  }
}
